[package]
name = "parser"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.54", features = ["derive"] }

[[bin]]
name = "comparer"
path = "src/bin/comparer.rs"

[[bin]]
name = "converter"
path = "src/bin/converter.rs"
